server:
  port: 8080
spring:
  application:
    name: GATEWAY-SERVICE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:123@localhost:8800/eureka
  instance:
    hostname: localhost